// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class WatchRemember
{
        public const string achievement_clear_level_10 = "CgkIjvLWuNsBEAIQCw"; // <GPGSID>
        public const string package_name = "com.NewDayX.WatchRemember"; // <GPGSID>
        public const string achievement_clear_level_1 = "CgkIjvLWuNsBEAIQAg"; // <GPGSID>
        public const string achievement_clear_level_2 = "CgkIjvLWuNsBEAIQAw"; // <GPGSID>
        public const string achievement_clear_level_3 = "CgkIjvLWuNsBEAIQBA"; // <GPGSID>
        public const string achievement_clear_level_4 = "CgkIjvLWuNsBEAIQBQ"; // <GPGSID>
        public const string achievement_clear_level_5 = "CgkIjvLWuNsBEAIQBg"; // <GPGSID>
        public const string achievement_clear_level_6 = "CgkIjvLWuNsBEAIQBw"; // <GPGSID>
        public const string achievement_clear_level_7 = "CgkIjvLWuNsBEAIQCA"; // <GPGSID>
        public const string achievement_clear_level_8 = "CgkIjvLWuNsBEAIQCQ"; // <GPGSID>
        public const string achievement_clear_level_9 = "CgkIjvLWuNsBEAIQCg"; // <GPGSID>
        public const string leaderboard_best_stage = "CgkIjvLWuNsBEAIQDQ"; // <GPGSID>
        public const string leaderboard_best_score = "CgkIjvLWuNsBEAIQDg"; // <GPGSID>

}

